version: '3.8'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  frontend_node_modules:
  backend_node_modules:
  mongo_data:

networks:
  app-network:
    driver: bridge
