version: '3.8'
services:
  frontend-mrt:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
  backend-mrt:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
        - backend_node_modules:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo-mrt
  mongo-mrt:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  frontend_node_modules:
  backend_node_modules:
  mongo_data:
